name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        run: |
          npm install --legacy-peer-deps
      - name: Lint
        run: |
          npm run lint
      - name: Test
        env:
          CI: true
        run: |
          npm test -- --ci --coverage
      - name: Coverage
        if: matrix.node-version == '16.x' && github.actor != 'dependabot[bot]'
        uses: coverallsapp/github-action@v1.1.2
        with:
          flag-name: run-${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './artifacts/coverage/lcov.info'
      - name: Build
        run: |
          npm run build
      - name: Integration
        run: |
          npm run e2e
      - name: Bundle
        if: github.actor != 'dependabot[bot]'
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: |
          npm run bundlewatch
      - name: Deploy
        if: matrix.node-version == '16.x' && github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run release
